# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/fluent-react-utils

    steps:
      - checkout

      - run: sudo npm install -g lerna
      - run: lerna bootstrap
